baseURL = "https://spinspin.dev/"
title = "SpinRodriguez"
headerTitle1 = "Spin"
headerTitle2 = "Rodriguez"
theme = "hugo-coder"
languageCode = "en-us"
defaultContentLanguage = "en"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true

[params]
author = "Spin Rodriguez"
description = "Spin's little dev corner of the internet"
keywords = "blog,developer,personal"
info = "Data and Other Things"
avatarURL = "images/avatar.jpg"
# footerContent = "Built out of curiosity."
dateFormat = "January 2, 2006"
hideFooter = false
hideCredits = true
hideCopyright = false
since = 2021

# Right To Left, shift content direction for languagues such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "dark"

# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false

# Series see also post count
maxSeeAlsoItems = 5
# Enable Twemoji
enableTwemoji = false
# Custom CSS
customCSS = ["css/main.css","css/resume.css"]
# Custom SCSS
customSCSS = []
# Custom JS
customJS = []

[params.csp]
childsrc = ["'self'"]
fontsrc = ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/"]
formaction = ["'self'"]
framesrc = ["'self'"]
imgsrc = ["'self'"]
objectsrc = ["'none'"]
stylesrc = [
  "'self'",
  "'unsafe-inline'",
  "https://fonts.googleapis.com/",
  "https://cdn.jsdelivr.net/"
]
scriptsrc = ["'self'", "'unsafe-inline'", "https://www.google-analytics.com"]
prefetchsrc = ["'self'"]
# connect-src directive – defines valid targets for to XMLHttpRequest (AJAX), WebSockets or EventSource
connectsrc = ["'self'", "https://www.google-analytics.com"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-github"
weight = 1
url = "https://github.com/favorspin/"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-linkedin"
weight = 2
url = "https://www.linkedin.com/in/spin-rodriguez/"

[[params.social]]
name = "Instagram"
icon = "fa fa-instagram"
weight = 3
url = "https://instagram.com/earthboudoir"

[[params.social]]
name = "RSS"
icon = "fa fa-rss"
weight = 4
url = "/index.xml"
rel = "alternate"
type = "application/rss+xml"

# [[params.social]]
# name = "Gitlab"
# icon = "fa fa-gitlab"
# weight = 5
# url = ""

# [[params.social]]
# name = "Twitter"
# icon = "fa fa-twitter"
# weight = 6
# url = ""

# [[params.social]]
# name = "Medium"
# icon = "fa fa-medium"
# weight = 7
# url = ""

[languages.en]
languageName = ":us:"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

# [[languages.en.menu.main]]
# name = "Blog"
# weight = 2
# url = "posts/"

# [[languages.en.menu.main]]
# name = "Projects"
# weight = 3
# url = "projects/"

[[languages.en.menu.main]]
name = "Résumé"
weight = 4
url = "resume/"

# [[languages.en.menu.main]]
# name = "Contact"
# weight = 5
# url = "contact/"

[markup.goldmark.renderer]
unsafe= true